backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - label: "Perfil"
    name: "profile"
    files:
      - label: "Perfil"
        name: "profile"
        file: "content/settings/profile.json"
        fields:
          - { label: "Nome (PT)", name: "name_pt", widget: string }
          - { label: "Nome (EN)", name: "name_en", widget: string }
          - { label: "Título (PT)", name: "title_pt", widget: string }
          - { label: "Título (EN)", name: "title_en", widget: string }
          - { label: "Bio (PT)", name: "bio_pt", widget: text }
          - { label: "Bio (EN)", name: "bio_en", widget: text }
          - { label: "Email", name: "email", widget: string }
          - { label: "Avatar", name: "avatar", widget: image }
          - { label: "LinkedIn", name: "linkedin", widget: string, required: false }
          - { label: "GitHub", name: "github", widget: string, required: false }
          - { label: "Twitter", name: "twitter", widget: string, required: false }
  - label: "Habilidades"
    name: "skills"
    files:
      - label: "Skills"
        name: "skills"
        file: "content/data/skills.json"
        fields:
          - name: skills_list
            label: "Lista de Habilidades"
            widget: list
            fields:
              - { label: "Nome", name: "name", widget: string }
              - { label: "Porcentagem", name: "percentage", widget: number }
  - label: "Projetos"
    name: "projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "ID", name: "id", widget: string }
      - { label: "Título (PT)", name: "title_pt", widget: string }
      - { label: "Título (EN)", name: "title_en", widget: string }
      - { label: "Descrição Curta (PT)", name: "shortDescription_pt", widget: text }
      - { label: "Descrição Curta (EN)", name: "shortDescription_en", widget: text }
      - { label: "Descrição (PT)", name: "description_pt", widget: text }
      - { label: "Descrição (EN)", name: "description_en", widget: text }
      - { label: "Imagem", name: "imageUrl", widget: image }
      - { label: "Categoria", name: "category", widget: string }
      - { label: "Tecnologias", name: "technologies", widget: list, field: {label: "Tecnologia", name: "tech", widget: string} }
      - { label: "GitHub", name: "githubUrl", widget: string, required: false }
      - { label: "Demo", name: "liveUrl", widget: string, required: false }
      - { label: "Destaque", name: "featured", widget: boolean, required: false }
      - { label: "Criado em", name: "createdAt", widget: datetime }
      - { label: "Atualizado em", name: "updatedAt", widget: datetime }
  - label: "Blog Posts"
    name: "posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título (PT)", name: "title_pt", widget: string }
      - { label: "Título (EN)", name: "title_en", widget: string }
      - { label: "Resumo (PT)", name: "summary_pt", widget: text }
      - { label: "Resumo (EN)", name: "summary_en", widget: text }
      - { label: "Data Publicação", name: "publicationDate", widget: datetime }
      - { label: "Imagem Capa", name: "imageUrl", widget: image, required: false }
      - { label: "Categoria", name: "category", widget: string }
      - { label: "Tags", name: "tags", widget: list, required: false }
      - { label: "Autor", name: "author", widget: object, fields: [{label: "Nome", name: "name", widget: string}, {label: "Avatar", name: "avatar", widget: image, required: false}], required: false }
      - { label: "Publicado", name: "published", widget: boolean, required: false }
      - { label: "Corpo (PT)", name: "body_pt", widget: markdown }
      - { label: "Corpo (EN)", name: "body_en", widget: markdown } 