name: Notify Discord

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed, reopened]
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
          -d '{
            "username": "Portfolio Bot",
            "avatar_url": "https://github.com/caiolombello.png",
            "embeds": [{
              "title": "${{ github.event_name == 'push' && '🚀 New Push' || '🔄 Pull Request' }}",
              "description": "**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref_name }}\n**Event:** ${{ github.event_name }}\n${{ github.event.pull_request && format('**PR Title:** {0}\n**PR State:** {1}\n', github.event.pull_request.title, github.event.pull_request.state) || '' }}\n**Author:** ${{ github.actor }}\n**Commit Message:** ${{ github.event.head_commit.message || github.event.pull_request.title }}\n\n[View Changes](${{ github.event.pull_request.html_url || github.event.head_commit.url }})",
              "color": ${{ github.event_name == 'push' && '5865F2' || (github.event.pull_request.merged && '9C84EF' || (github.event.pull_request.state == 'closed' && 'ED4245' || '57F287')) }}
            }]
          }' $DISCORD_WEBHOOK
